language: rust
addons:
  apt:
    packages:
    - libegl1-mesa-dev
    - libgtk-3-dev
    - libsdl2-dev
    - cmake
script:
  - cargo build
  - cargo build -p pathfinder_webgl --target wasm32-unknown-unknown
  - cargo test
env:
  global:
    - HARFBUZZ_SYS_NO_PKG_CONFIG=true
