[package]
name = "demo"
version = "0.1.0"
edition = "2018"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[features]
pf-gl = ["pathfinder_demo/pf-gl"]
pf-no-simd = ["pathfinder_simd/pf-no-simd"]

[dependencies]
color-backtrace = "0.3"
gl = "0.14"
nfd = "0.0.4"
pretty_env_logger = "0.4"
sdl2 = "0.33"
sdl2-sys = "0.33"

[dependencies.pathfinder_demo]
path = "../common"

[dependencies.pathfinder_geometry]
path = "../../geometry"

[dependencies.pathfinder_gl]
path = "../../gl"

[dependencies.pathfinder_gpu]
path = "../../gpu"

[dependencies.pathfinder_simd]
path = "../../simd"

[target.'cfg(target_os = "macos")'.dependencies]
foreign-types = "0.3"
metal = "0.17"

[target.'cfg(target_os = "macos")'.dependencies.pathfinder_metal]
path = "../../metal"

[target.'cfg(not(windows))'.dependencies]
jemallocator = "0.3"
