[package]
name = "canvas_nanovg"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition = "2018"

[dependencies]
arrayvec = "0.5"
font-kit = "0.6"
gl = "0.14"
sdl2 = "0.33"
sdl2-sys = "0.33"

[dependencies.image]
version = "0.23"
default-features = false
features = ["png"]

[dependencies.log]
version = "0.4"
features = ["release_max_level_info"]

[dependencies.pathfinder_canvas]
path = "../../canvas"
features = ["pf-text"]

[dependencies.pathfinder_color]
path = "../../color"

[dependencies.pathfinder_content]
path = "../../content"

[dependencies.pathfinder_geometry]
path = "../../geometry"

[dependencies.pathfinder_gl]
path = "../../gl"

[dependencies.pathfinder_gpu]
path = "../../gpu"

[dependencies.pathfinder_renderer]
path = "../../renderer"

[dependencies.pathfinder_resources]
path = "../../resources"

[dependencies.pathfinder_simd]
path = "../../simd"

[target.'cfg(not(windows))'.dependencies]
jemallocator = "0.3"
