[package]
name = "pathfinder_renderer"
version = "0.1.0"
edition = "2018"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[features]
debug_ui = []

[dependencies]
bitflags = "1.0"
byteorder = "1.2"
hashbrown = "0.7"
rayon = "1.0"
serde = "1.0"
serde_json = "1.0"
smallvec = "1.2"

[dependencies.log]
version = "0.4"

[dependencies.pathfinder_color]
path = "../color"

[dependencies.pathfinder_content]
path = "../content"

[dependencies.pathfinder_geometry]
path = "../geometry"

[dependencies.pathfinder_gpu]
path = "../gpu"

[dependencies.pathfinder_resources]
path = "../resources"

[dependencies.pathfinder_simd]
path = "../simd"

[dependencies.pathfinder_ui]
path = "../ui"

[dev-dependencies]
quickcheck = "0.9"
